/*
	Generated by KBEngine!
	Please do not modify this file!
	Please inherit this module, such as: (class Avatar : AvatarBase)
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Avatar.def
	public abstract class AvatarBase : Entity
	{
		public EntityBaseMailbox_AvatarBase baseMailbox = null;
		public EntityCellMailbox_AvatarBase cellMailbox = null;

		public string roleName = "";
		public virtual void onRoleNameChanged(string oldValue) {}
		public UInt16 roleType = 0;
		public virtual void onRoleTypeChanged(UInt16 oldValue) {}


		public override void onGetBase()
		{
			baseMailbox = new EntityBaseMailbox_AvatarBase();
			baseMailbox.id = id;
			baseMailbox.className = className;
		}

		public override void onGetCell()
		{
			cellMailbox = new EntityCellMailbox_AvatarBase();
			cellMailbox.id = id;
			cellMailbox.className = className;
		}

		public override void onLoseCell()
		{
			cellMailbox = null;
		}

		public override EntityMailbox getBaseMailbox()
		{
			return baseMailbox;
		}

		public override EntityMailbox getCellMailbox()
		{
			return cellMailbox;
		}

		public override void onRemoteMethodCall(Method method, MemoryStream stream)
		{
			switch(method.methodUtype)
			{
				default:
					break;
			};
		}

		public override void onUpdatePropertys(Property prop, MemoryStream stream)
		{
			switch(prop.properUtype)
			{
				case 40001:
					Vector3 oldval_direction = direction;
					direction = stream.readVector3();

					if(prop.isBase())
					{
						if(inited)
							onDirectionChanged(oldval_direction);
					}
					else
					{
						if(inWorld)
							onDirectionChanged(oldval_direction);
					}

					break;
				case 40000:
					Vector3 oldval_position = position;
					position = stream.readVector3();

					if(prop.isBase())
					{
						if(inited)
							onPositionChanged(oldval_position);
					}
					else
					{
						if(inWorld)
							onPositionChanged(oldval_position);
					}

					break;
				case 6:
					string oldval_roleName = roleName;
					roleName = stream.readUnicode();

					if(prop.isBase())
					{
						if(inited)
							onRoleNameChanged(oldval_roleName);
					}
					else
					{
						if(inWorld)
							onRoleNameChanged(oldval_roleName);
					}

					break;
				case 7:
					UInt16 oldval_roleType = roleType;
					roleType = stream.readUint16();

					if(prop.isBase())
					{
						if(inited)
							onRoleTypeChanged(oldval_roleType);
					}
					else
					{
						if(inWorld)
							onRoleTypeChanged(oldval_roleType);
					}

					break;
				case 40002:
					UInt32 spaceID = stream.readUint32();
					spaceID = 0;
					break;
				default:
					break;
			};
		}

		public override void callPropertysSetMethods()
		{
			ScriptModule sm = EntityDef.moduledefs[className];
			Dictionary<UInt16, Property> pdatas = sm.idpropertys;

			Vector3 oldval_direction = direction;
			Property prop_direction = pdatas[1];
			if(prop_direction.isBase())
			{
				if(inited && !inWorld)
					onDirectionChanged(oldval_direction);
			}
			else
			{
				if(inWorld)
				{
					if(prop_direction.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onDirectionChanged(oldval_direction);
					}
				}
			}

			Vector3 oldval_position = position;
			Property prop_position = pdatas[0];
			if(prop_position.isBase())
			{
				if(inited && !inWorld)
					onPositionChanged(oldval_position);
			}
			else
			{
				if(inWorld)
				{
					if(prop_position.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onPositionChanged(oldval_position);
					}
				}
			}

			string oldval_roleName = roleName;
			Property prop_roleName = pdatas[3];
			if(prop_roleName.isBase())
			{
				if(inited && !inWorld)
					onRoleNameChanged(oldval_roleName);
			}
			else
			{
				if(inWorld)
				{
					if(prop_roleName.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRoleNameChanged(oldval_roleName);
					}
				}
			}

			UInt16 oldval_roleType = roleType;
			Property prop_roleType = pdatas[4];
			if(prop_roleType.isBase())
			{
				if(inited && !inWorld)
					onRoleTypeChanged(oldval_roleType);
			}
			else
			{
				if(inWorld)
				{
					if(prop_roleType.isOwnerOnly() && !isPlayer())
					{
					}
					else
					{
						onRoleTypeChanged(oldval_roleType);
					}
				}
			}

		}
	}
}