/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseMailbox_AccountBase : EntityMailbox
	{
		public EntityBaseMailbox_AccountBase() : base()
		{
			type = MAILBOX_TYPE.MAILBOX_TYPE_BASE;
		}

		public void EntryFBSceneRequest(UInt32 arg1)
		{
			Bundle pBundle = newMail("EntryFBSceneRequest");
			if(pBundle == null)
				return;

			bundle.writeUint32(arg1);
			postMail(null);
		}

		public void QueryPlayerCountRequest()
		{
			Bundle pBundle = newMail("QueryPlayerCountRequest");
			if(pBundle == null)
				return;

			postMail(null);
		}

		public void ReCreateAccountRequest(UInt16 arg1, string arg2)
		{
			Bundle pBundle = newMail("ReCreateAccountRequest");
			if(pBundle == null)
				return;

			bundle.writeUint16(arg1);
			bundle.writeString(arg2);
			postMail(null);
		}

		public void reqHasEnteredBattlefiled()
		{
			Bundle pBundle = newMail("reqHasEnteredBattlefiled");
			if(pBundle == null)
				return;

			postMail(null);
		}

	}

	public class EntityCellMailbox_AccountBase : EntityMailbox
	{
		public EntityCellMailbox_AccountBase() : base()
		{
			type = MAILBOX_TYPE.MAILBOX_TYPE_CELL;
		}

	}
	}
