/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/FBBattleField.def
	public class EntityBaseMailbox_FBBattleFieldBase : EntityMailbox
	{
		public EntityBaseMailbox_FBBattleFieldBase() : base()
		{
			type = MAILBOX_TYPE.MAILBOX_TYPE_BASE;
		}

	}

	public class EntityCellMailbox_FBBattleFieldBase : EntityMailbox
	{
		public EntityCellMailbox_FBBattleFieldBase() : base()
		{
			type = MAILBOX_TYPE.MAILBOX_TYPE_CELL;
		}

	}
	}
